hostname: memos.xargs.dev
namespace: memos
litestream:
  version: 0.3.9
images:
  handroll:
    name: oci.xargs.dev/handroll/memos
    tag: 0.11.0_litestream-0.3.9
  upstream:
    name: ${DOCKERHUB}/neosmemo/memos
    tag: 0.11.0
app:
  name: memos
  version: 0.11.0
  port: 5230
  exec: "./memos --mode prod --port 5230"
  dataPath: /var/opt/memos
  dbPath: /var/opt/memos/memos_prod.db
